# Form implementation generated from reading ui file 'openCV_GUI.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 900)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Main vertical layout
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        # Scroll Area
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")

        # Scroll area widget contents
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        # Vertical layout for scroll contents
        self.scrollLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollLayout.setObjectName("scrollLayout")

        # Window Capture Section
        self.winCapGroup = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.winCapGroup.setObjectName("winCapGroup")
        self.winCapLayout = QtWidgets.QVBoxLayout(self.winCapGroup)

        # Window selection
        self.winCapRow1 = QtWidgets.QHBoxLayout()
        self.WinCapLabel = QtWidgets.QLabel(parent=self.winCapGroup)
        self.WinCapLabel.setObjectName("WinCapLabel")
        self.winCapRow1.addWidget(self.WinCapLabel)

        self.WinCapBox = QtWidgets.QComboBox(parent=self.winCapGroup)
        self.WinCapBox.setObjectName("WinCapBox")
        self.winCapRow1.addWidget(self.WinCapBox)

        self.pushButton = QtWidgets.QPushButton(parent=self.winCapGroup)
        self.pushButton.setObjectName("pushButton")
        self.winCapRow1.addWidget(self.pushButton)
        self.winCapLayout.addLayout(self.winCapRow1)

        # Crop controls
        self.cropControls = QtWidgets.QGridLayout()

        self.LWinCapLabel = QtWidgets.QLabel(parent=self.winCapGroup)
        self.LWinCapLabel.setObjectName("LWinCapLabel")
        self.LeftWinCap = QtWidgets.QSlider(parent=self.winCapGroup)
        self.LeftWinCap.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.LeftWinCap.setMaximum(100)
        self.LeftWinCap.setObjectName("LeftWinCap")
        self.cropControls.addWidget(self.LWinCapLabel, 0, 0)
        self.cropControls.addWidget(self.LeftWinCap, 0, 1)

        self.RWinCapLabel = QtWidgets.QLabel(parent=self.winCapGroup)
        self.RWinCapLabel.setObjectName("RWinCapLabel")
        self.RightWinCap = QtWidgets.QSlider(parent=self.winCapGroup)
        self.RightWinCap.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.RightWinCap.setMaximum(100)
        self.RightWinCap.setObjectName("RightWinCap")
        self.cropControls.addWidget(self.RWinCapLabel, 1, 0)
        self.cropControls.addWidget(self.RightWinCap, 1, 1)

        self.TopWinCapLabel = QtWidgets.QLabel(parent=self.winCapGroup)
        self.TopWinCapLabel.setObjectName("TopWinCapLabel")
        self.TopWinCap = QtWidgets.QSlider(parent=self.winCapGroup)
        self.TopWinCap.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.TopWinCap.setMaximum(100)
        self.TopWinCap.setObjectName("TopWinCap")
        self.cropControls.addWidget(self.TopWinCapLabel, 2, 0)
        self.cropControls.addWidget(self.TopWinCap, 2, 1)

        self.BotWinCapLabel = QtWidgets.QLabel(parent=self.winCapGroup)
        self.BotWinCapLabel.setObjectName("BotWinCapLabel")
        self.BotWinCap = QtWidgets.QSlider(parent=self.winCapGroup)
        self.BotWinCap.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.BotWinCap.setMaximum(100)
        self.BotWinCap.setObjectName("BotWinCap")
        self.cropControls.addWidget(self.BotWinCapLabel, 3, 0)
        self.cropControls.addWidget(self.BotWinCap, 3, 1)

        self.winCapLayout.addLayout(self.cropControls)
        self.scrollLayout.addWidget(self.winCapGroup)

        # HSV Filter Section
        self.hsvGroup = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.hsvGroup.setObjectName("hsvGroup")
        self.hsvLayout = QtWidgets.QHBoxLayout(self.hsvGroup)

        self.HSVFilterLabel = QtWidgets.QLabel(parent=self.hsvGroup)
        self.HSVFilterLabel.setObjectName("HSVFilterLabel")
        self.hsvLayout.addWidget(self.HSVFilterLabel)

        self.HSVGray = QtWidgets.QRadioButton(parent=self.hsvGroup)
        self.HSVGray.setChecked(True)
        self.HSVGray.setObjectName("HSVGray")
        self.hsvLayout.addWidget(self.HSVGray)

        self.HSVColor = QtWidgets.QRadioButton(parent=self.hsvGroup)
        self.HSVColor.setObjectName("HSVColor")
        self.hsvLayout.addWidget(self.HSVColor)

        self.scrollLayout.addWidget(self.hsvGroup)

        # Display Options Section
        self.displayGroup = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.displayGroup.setObjectName("displayGroup")
        self.displayLayout = QtWidgets.QGridLayout(self.displayGroup)

        self.DrawRecLabel = QtWidgets.QLabel(parent=self.displayGroup)
        self.DrawRecLabel.setObjectName("DrawRecLabel")
        self.DrawRecBool = QtWidgets.QCheckBox(parent=self.displayGroup)
        self.DrawRecBool.setObjectName("DrawRecBool")
        self.displayLayout.addWidget(self.DrawRecLabel, 0, 0)
        self.displayLayout.addWidget(self.DrawRecBool, 0, 1)

        self.ShowFPSLabel = QtWidgets.QLabel(parent=self.displayGroup)
        self.ShowFPSLabel.setObjectName("ShowFPSLabel")
        self.ShowFPSBool = QtWidgets.QCheckBox(parent=self.displayGroup)
        self.ShowFPSBool.setObjectName("ShowFPSBool")
        self.displayLayout.addWidget(self.ShowFPSLabel, 1, 0)
        self.displayLayout.addWidget(self.ShowFPSBool, 1, 1)

        self.scrollLayout.addWidget(self.displayGroup)

        # Steps Container
        self.stepsContainer = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.stepsLayout = QtWidgets.QVBoxLayout(self.stepsContainer)
        self.stepsLayout.setObjectName("stepsLayout")
        self.scrollLayout.addWidget(self.stepsContainer)

        # Add Step Controls
        self.addStepGroup = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        self.addStepGroup.setObjectName("addStepGroup")
        self.addStepLayout = QtWidgets.QHBoxLayout(self.addStepGroup)

        self.addStepComboBox = QtWidgets.QComboBox(parent=self.addStepGroup)
        self.addStepComboBox.addItems(["Add Target Image", "Add Action"])
        self.addStepComboBox.setObjectName("addStepComboBox")
        self.addStepLayout.addWidget(self.addStepComboBox)

        self.AddStepBtn = QtWidgets.QPushButton(parent=self.addStepGroup)
        self.AddStepBtn.setObjectName("AddStepBtn")
        self.addStepLayout.addWidget(self.AddStepBtn)

        self.scrollLayout.addWidget(self.addStepGroup)

        # Run Macro Button
        self.RunMacroBtn = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.RunMacroBtn.setObjectName("RunMacroBtn")
        self.RunMacroBtn.setText("Run Macro")
        self.scrollLayout.addWidget(self.RunMacroBtn)

        # Find Targets Btn
        self.FindTargetsBtn = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.FindTargetsBtn.setObjectName("FindTargetsBtn")
        self.FindTargetsBtn.setText("Find Targets")
        self.scrollLayout.addWidget(self.FindTargetsBtn)

        # Spacer to push content up
        self.scrollLayout.addStretch()

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenCV Window Capture"))
        self.winCapGroup.setTitle(_translate("MainWindow", "Window Capture"))
        self.WinCapLabel.setText(_translate("MainWindow", "Window:"))
        self.pushButton.setText(_translate("MainWindow", "Run CV"))
        self.LWinCapLabel.setText(_translate("MainWindow", "Left Crop %"))
        self.RWinCapLabel.setText(_translate("MainWindow", "Right Crop %"))
        self.TopWinCapLabel.setText(_translate("MainWindow", "Top Crop %"))
        self.BotWinCapLabel.setText(_translate("MainWindow", "Bottom Crop %"))
        self.hsvGroup.setTitle(_translate("MainWindow", "HSV Filter"))
        self.HSVFilterLabel.setText(_translate("MainWindow", "Filter Type:"))
        self.HSVGray.setText(_translate("MainWindow", "Grayscale"))
        self.HSVColor.setText(_translate("MainWindow", "Color"))
        self.displayGroup.setTitle(_translate("MainWindow", "Display Options"))
        self.DrawRecLabel.setText(_translate("MainWindow", "Draw Rectangles:"))
        self.DrawRecBool.setText(_translate("MainWindow", "Enable"))
        self.ShowFPSLabel.setText(_translate("MainWindow", "Show FPS:"))
        self.ShowFPSBool.setText(_translate("MainWindow", "Enable"))
        self.addStepGroup.setTitle(_translate("MainWindow", "Add Step"))
        self.AddStepBtn.setText(_translate("MainWindow", "Add Step"))
